name: Java Cucumber Selenium CI

# Kör workflowen på push mot main eller vid Pull Request mot main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Vi använder en officiell Ubuntu-miljö
    runs-on: ubuntu-latest

    steps:
      # 1) Hämta ner all kod från repo:t
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Installera Java (samma version som du har i din pom.xml)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'      # AdoptOpenJDK / Temurin 
          java-version: '11'          # Eller 17 om du använder den

      # 3) (Valfritt men oftast nödvändigt för Selenium) Starta en virtuell X-server (Xvfb)
      #    Så att Chrome kan köras i en “headless” display utan GUI
      - name: Setup Xvfb (för Selenium)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      # 4) Bygg och kompilerar projektet
      - name: Build project with Maven
        run: mvn clean compile -q

      # 5) Kör alla tester (enhetstester, integrationstester, Cucumber-tester osv.)
      - name: Run tests
        run: mvn test -q

      # 6) (Valfritt) Om du vill spara t.ex. test-reports som artefakter:
      # - name: Publish test reports
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: surefire-reports
      #     path: target/surefire-reports/**/*.xml
